# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: online/proto/model_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fonline/proto/model_config.proto\"B\n\x11ModelBlockProfile\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07latency\x18\x02 \x01(\x03\x12\x10\n\x08\x61\x63\x63uracy\x18\x03 \x01(\x02\"~\n\x0bModelConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64ims\x18\x02 \x03(\x03\x12)\n\rblock_profile\x18\x03 \x03(\x0b\x32\x12.ModelBlockProfile\x12(\n\x0c\x65xit_profile\x18\x04 \x03(\x0b\x32\x12.ModelBlockProfileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'online.proto.model_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODELBLOCKPROFILE']._serialized_start=35
  _globals['_MODELBLOCKPROFILE']._serialized_end=101
  _globals['_MODELCONFIG']._serialized_start=103
  _globals['_MODELCONFIG']._serialized_end=229
# @@protoc_insertion_point(module_scope)
